import fs from "fs";
import path from "path";

function escapeMarkdown(text = "") {
  return String(text || "").replace(/\r\n|\r|\n/g, " ").trim();
}

function formatParameter(param) {
  const req = param.required ? "(required)" : "(optional)";
  return `- **${param.name}**: ${param.type} ${req}  \n  ${escapeMarkdown(
    param.description || "",
  )}`;
}

export function generateMarkdownFromPayload(payload = {}) {
  const { contractId = "unknown", network = "", functions = [], customTypes = [] } = payload;
  const lines = [];

  lines.push(`# Contract Documentation: ${contractId}`);
  if (network) lines.push(`**Network**: ${network}`);
  lines.push(`**Generated**: ${new Date().toISOString()}`);
  lines.push("\n---\n");

  if (payload.warnings && payload.warnings.length > 0) {
    lines.push("**Warnings**:\n");
    for (const w of payload.warnings) lines.push(`- ${escapeMarkdown(w)}`);
    lines.push("\n---\n");
  }

  if (customTypes && customTypes.length > 0) {
    lines.push("## Custom Types\n");
    for (const t of customTypes) {
      lines.push(`### ${t.name}`);
      if (t.description) lines.push(escapeMarkdown(t.description));
      lines.push(`**Summary**: ${t.summary || ""}`);
      lines.push("\n");
    }
    lines.push("---\n");
  }

  lines.push("## Functions\n");

  for (const fn of functions) {
    lines.push(`### ${fn.name}`);
    if (fn.summary) lines.push(`**Summary**: ${escapeMarkdown(fn.summary)}`);
    if (fn.doc) lines.push(`**Description**: ${escapeMarkdown(fn.doc)}`);

    lines.push("\n**Signature**:\n");
    lines.push(`\`${fn.signature || fn.name}\``);

    if (fn.parameters && fn.parameters.length > 0) {
      lines.push("\n**Parameters**:\n");
      for (const p of fn.parameters) lines.push(formatParameter(p));
    } else {
      lines.push("\n**Parameters**: None\n");
    }

    lines.push(`\n**Returns**: ${fn.returnType || fn.returnTypes?.join(" | ") || "void"}`);

    // Usage examples (JS snippet)
    lines.push("\n**Usage (JS)**:\n");
    const argsExample = (fn.parameters || [])
      .map((p) => `${p.name}: /* ${p.type} */ "REPLACE"`)
      .join(", ");

    lines.push("```js");
    lines.push("// Example: invoke via api/examples/js/invoke-contract.mjs style");
    lines.push("import { invoke } from 'stellar-dev-dashboard/api/examples/js/invoke-contract.mjs' // adapt path");
    lines.push(
      `// invoke({ contractId: '${contractId}', functionName: '${fn.name}', args: [{ ${
        argsExample
      } }] })`,
    );
    lines.push("```");

    // CLI example (generic)
    lines.push("\n**Usage (CLI)**:\n");
    lines.push("```sh");
    lines.push(
      `# TODO: Replace with actual CLI if available. Example form: cli invoke --contract ${contractId} --fn ${fn.name} --arg name=value`,
    );
    lines.push("```");

    lines.push("---\n");
  }

  lines.push("\n---\n");
  lines.push(
    "Generated by the Stellar Dev Dashboard contract documentation generator. Users can edit and refine these docs; feedback can be collected to improve future generations.",
  );

  return lines.join("\n");
}

export async function generateAndSave(contractId, network = "testnet", outPath = null) {
  // Dynamically import the contract parser to avoid requiring @stellar/stellar-sdk at module load time
  let parseContractWasm = null;
  try {
    const mod = await import("./contractInvoker.js");
    parseContractWasm = mod.parseContractWasm;
  } catch (err) {
    throw new Error(
      `Could not load contract parser. Ensure dependencies are installed. (${err.message || err})`,
    );
  }

  const payload = await parseContractWasm(contractId, network);
  const md = generateMarkdownFromPayload(payload);

  const dir = outPath ? path.dirname(outPath) : path.join(process.cwd(), "docs", "contracts");
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const filename = outPath || path.join(dir, `${contractId}.md`);
  fs.writeFileSync(filename, md, "utf8");
  return filename;
}
