/**
 * refactoring/recommender.ts
 *
 * Top-level orchestrator that converts a set of FileTarget inputs into a
 * Prioritized list of refactoring opportunities, hotspots, and a quality
 * score. This module is the public façade the UI consumes.
 */

import { analyzeFiles } from './codeAnalyzer.js';
import { runDetectors } from './refactoringPatterns.js';
import {
  buildBaseline,
  computeImpact,
  computePriority,
  maintainabilityIndex,
  rankSuggestions,
  type CorpusBaseline,
} from './impactAssessment.js';
import { assessSafety, buildSafetyContext, type SafetyContext } from './safetyAnalysis.js';
import type {
  FileTarget,
  Hotspot,
  RefactorKind,
  RefactorReport,
  RefactoringSuggestion,
  RecommendOptions,
} from './types.js';

// ---------------------------------------------------------------------------
// Pseudo Isolation Forest for hotspot discovery
// ---------------------------------------------------------------------------

/**
 * Lightweight Isolation Forest implementation. Each tree splits on a
 * random feature at a random value within its observed range.  Anomaly
 * score is `2^(-mean_path_length / c(n))`. This is the same family as the
 * one used in the existing transaction-patterns module — kept
 * self-contained so the recommender does not pull in TFJS at runtime.
 */
interface IFNode {
  feature: number;
  value: number;
  size: number;
  left: IFNode | null;
  right: IFNode | null;
}

class IsolationForest {
  private trees: IFNode[] = [];
  constructor(
    private nTrees: number = 60,
    private subSampleSize: number = 64
  ) {}

  fit(X: number[][]): void {
    if (X.length === 0) return;
    const n = X.length;
    const limit = Math.ceil(Math.log2(Math.max(this.subSampleSize, 2)));
    this.trees = [];
    for (let t = 0; t < this.nTrees; t++) {
      const idx: number[] = [];
      while (idx.length < Math.min(this.subSampleSize, n)) {
        const r = Math.floor(Math.random() * n);
        if (!idx.includes(r)) idx.push(r);
      }
      const sample = idx.map((i) => X[i]);
      this.trees.push(this.buildTree(sample, 0, limit, X[0].length));
    }
  }

  private buildTree(
    X: number[][],
    curDepth: number,
    limit: number,
    featureCount: number
  ): IFNode {
    if (X.length <= 1 || curDepth >= limit) {
      return { feature: -1, value: 0, size: X.length, left: null, right: null };
    }
    const featureIdx = Math.floor(Math.random() * featureCount);
    let min = Infinity;
    let max = -Infinity;
    for (const row of X) {
      const v = row[featureIdx];
      if (v < min) min = v;
      if (v > max) max = v;
    }
    if (!Number.isFinite(min) || !Number.isFinite(max) || min === max) {
      return { feature: -1, value: 0, size: X.length, left: null, right: null };
    }
    const value = min + Math.random() * (max - min);
    const left = X.filter((r) => r[featureIdx] < value);
    const right = X.filter((r) => r[featureIdx] >= value);
    return {
      feature: featureIdx,
      value,
      size: X.length,
      left: this.buildTree(left, curDepth + 1, limit, featureCount),
      right: this.buildTree(right, curDepth + 1, limit, featureCount),
    };
  }

  score(x: number[]): number {
    if (!this.trees.length) return 0;
    const lengths = this.trees.map((t) => pathLen(x, t, 0));
    const avg = lengths.reduce((s, l) => s + l, 0) / lengths.length;
    const n = Math.min(this.subSampleSize, 256);
    const cn = cFactor(n);
    if (cn === 0) return 0;
    return Math.pow(2, -avg / cn);
  }
}

function pathLen(x: number[], node: IFNode, depth: number): number {
  if (!node.left || !node.right) {
    return depth + cFactor(Math.max(1, node.size));
  }
  const v = node.feature >= 0 ? x[node.feature] ?? 0 : 0;
  if (v < node.value && node.left) return pathLen(x, node.left, depth + 1);
  if (node.right) return pathLen(x, node.right, depth + 1);
  return depth + 1;
}

function cFactor(n: number): number {
  if (n <= 1) return 0;
  if (n === 2) return 1;
  return 2 * (Math.log(n - 1) + 0.5772156649) - (2 * (n - 1)) / n;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface RecommendInput {
  files: FileTarget[];
  options?: RecommendOptions;
  /** Files that are auto-generated and unsafe to edit (defaults to none) */
  autoGeneratedFiles?: Set<string>;
  /** Files exposed as public API (defaults to none) */
  publicApiFiles?: Set<string>;
}

export interface RecommendResult {
  report: RefactorReport;
  /** Per-file metrics for the dashboard UI */
  metrics: ReturnType<typeof analyzeFiles>;
  /** Suggestions after prioritization */
  suggestions: ReturnType<typeof rankSuggestions>;
  /** Suggestions sorted into quick wins */
  quickWins: ReturnType<typeof rankSuggestions>;
}

export function recommend(input: RecommendInput): RecommendResult {
  const filter = input.options?.fileFilter;
  const files = filter ? input.files.filter((f) => filter(f.path)) : input.files;
  const metrics = analyzeFiles(files);
  const metadata = buildFileMetadata(files);

  const safetyCtx: SafetyContext = buildSafetyContext(
    files,
    input.autoGeneratedFiles ?? new Set(),
    input.publicApiFiles ?? new Set()
  );

  const baseline = buildBaseline(metrics);
  const hotspots = detectHotspots(metrics, baseline);

  // Run detectors per file and combine suggestions.
  const allSuggestions: RefactoringSuggestion[] = [];
  for (const file of metrics) {
    const meta = metadata.get(file.path) ?? {
      coupling: 0,
      isPublicApi: false,
    };
    const source = meta.source ?? '';
    const raw = runDetectors({
      file,
      source,
      coveredByTests: safetyCtx.testCoverage.has(file.path),
      isPublicApi: meta.isPublicApi || input.publicApiFiles?.has(file.path) === true,
      coupling: meta.coupling,
    });
    for (const s of raw) {
      const impact = computeImpact(s, file, baseline);
      const safety = assessSafety(s, safetyCtx).safety;
      const priority = computePriority({ ...s, safety }, impact);
      allSuggestions.push({ ...s, safety, priority });
    }
  }

  const ranked = rankSuggestions(
    allSuggestions,
    Object.fromEntries(allSuggestions.map((s) => [s.id, s.safety]))
  );

  // Apply trims/locks
  const minPriority = input.options?.minPriority ?? 0;
  const max = input.options?.maxSuggestions ?? 200;
  const filtered = ranked.filter((s) => {
    if (s.priority < minPriority) return false;
    if (!input.options?.includeRisky && s.bucket === 'high-effort' && s.safety < 0.3)
      return false;
    return true;
  }).slice(0, max);

  const breakdown: Record<RefactorKind, number> = {
    'extract-function': 0,
    'simplify-conditional': 0,
    'reduce-complexity': 0,
    'remove-dead-code': 0,
    'rename-symbol': 0,
    'replace-any': 0,
    'split-file': 0,
    memoize: 0,
    'inline-trivial': 0,
    'consolidate-duplicates': 0,
    'reduce-parameters': 0,
    'modernize-syntax': 0,
    'add-type-annotation': 0,
    'flatten-nesting': 0,
  };
  for (const s of filtered) breakdown[s.kind] = (breakdown[s.kind] ?? 0) + 1;

  const totalLinesSaved = filtered.reduce((sum, s) => sum + s.linesSaved, 0);
  const totalComplexity = filtered.reduce((sum, s) => sum + s.complexityDelta, 0);
  const totalMaintainability = filtered.reduce(
    (sum, s) => sum + s.maintainabilityDelta,
    0
  );
  const avgAcceptance = filtered.length
    ? filtered.reduce((sum, s) => sum + s.confidence * s.safety, 0) / filtered.length
    : 0;
  const overallQuality = metrics.length
    ? metrics.reduce((sum, f) => sum + maintainabilityIndex(f), 0) /
      metrics.length
    : 0;

  const report: RefactorReport = {
    generatedAt: new Date().toISOString(),
    totalFilesAnalysed: metrics.length,
    totalFunctionsAnalysed: metrics.reduce((s, f) => s + f.functions.length, 0),
    totalSuggestions: filtered.length,
    averageAcceptanceProbability: Number((avgAcceptance * 100).toFixed(1)),
    codeQualityScore: Number(Math.max(0, Math.min(100, overallQuality)).toFixed(1)),
    hotspots,
    suggestions: filtered,
    issueBreakdown: breakdown,
    impact: {
      totalLinesSaved,
      totalComplexityReduction: totalComplexity,
      totalMaintainabilityGain: totalMaintainability,
    },
  };

  const quickWins = filtered.filter(
    (s) => s.priority >= 70 && s.safety >= 0.7 && s.effortMinutes <= 25
  );

  return { report, metrics, suggestions: filtered, quickWins };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

interface FileMeta {
  coupling: number;
  isPublicApi: boolean;
  /** Raw source text (used by detectors that need lexical inspection). */
  source: string;
}

/**
 * Cheap heuristic coupling counter: count `import` statements and the
 * number of distinct specifiers. Used to inform safety scoring.
 */
function buildFileMetadata(files: FileTarget[]): Map<string, FileMeta> {
  const out = new Map<string, FileMeta>();
  for (const f of files) {
    const imports = f.source.match(/^\s*import\b[^\n]*$/gm) ?? [];
    let coupling = 0;
    for (const line of imports) {
      const named = (line.match(/\{([^}]+)\}/g) ?? [])
        .join(',')
        .split(',')
        .filter(Boolean).length;
      coupling += named + 1;
    }
    const isPublicApi = /export\s+(default|function|class|const|interface|type)/m.test(
      f.source
    );
    out.set(f.path, { coupling, isPublicApi, source: f.source });
  }
  return out;
}

/**
 * Detect hotspot files via an unsupervised Isolation Forest trained on the
 * corpus. Files whose vector deviates furthest from the corpus are surfaced
 * for deeper manual review.
 */
function detectHotspots(
  metrics: ReturnType<typeof analyzeFiles>,
  baseline: CorpusBaseline
): Hotspot[] {
  if (metrics.length < 2) return [];

  // Feature vector: [loc, averageComplexity, anyUsage, duplicateLiteralScore]
  const X = metrics.map((f) => [
    f.loc,
    f.averageFunctionComplexity,
    f.anyUsage,
    f.duplicateLiteralScore,
  ]);

  const forest = new IsolationForest();
  forest.fit(X);

  return metrics
    .map((file, idx) => {
      const anomaly = forest.score(X[idx]);
      const factors: string[] = [];
      if (file.loc > baseline.averageLoc * 1.5) factors.push(`LOC ${file.loc} vs avg ${Math.round(baseline.averageLoc)}`);
      if (file.averageFunctionComplexity > baseline.averageComplexity * 1.5)
        factors.push(`avg complexity ${file.averageFunctionComplexity.toFixed(1)}`);
      if (file.anyUsage > baseline.averageAnyUsage * 1.5)
        factors.push(`${file.anyUsage} \`any\` annotations`);
      if (file.duplicateLiteralScore > 1) factors.push(`${file.duplicateLiteralScore} duplicate literals`);
      if (factors.length === 0) factors.push('Multivariate outlier');
      return {
        file: file.path,
        anomalyScore: Number(anomaly.toFixed(2)),
        contributingFactors: factors,
        baseline: {
          avgLoc: Math.round(baseline.averageLoc),
          avgComplexity: Number(baseline.averageComplexity.toFixed(1)),
          avgParams: Number(baseline.averageParameters.toFixed(1)),
        },
      };
    })
    .sort((a, b) => b.anomalyScore - a.anomalyScore)
    .slice(0, 10);
}
