/**
 * refactoring/safetyAnalysis.ts
 *
 * Determines the safety of applying a refactoring suggestion. The
 * safety score combines deterministic rules:
 *  • Test coverage of the file
 *  • Identifier fan-out / coupling
 *  • Presence of `any` types
 *  • Whether the target is part of the public API
 *  • Whether the file is auto-generated
 *
 * Rules are conservative: safe suggestions are inspected for risk
 * dimensions, and any unresolved risk lowers the score.
 */

import type { RefactoringSuggestion, SafetyAssessment } from './types.js';

export interface SafetyContext {
  /** Tests exist for the file's path */
  testCoverage: Map<string, number>;
  /** Set of files marked as auto-generated; these are unsafe to mutate */
  autoGeneratedFiles: Set<string>;
  /** Set of paths exported from the package; conservative public API */
  publicApiFiles: Set<string>;
}

export function buildSafetyContext(
  files: { path: string }[],
  autoGeneratedFiles: Set<string> = new Set(),
  publicApiFiles: Set<string> = new Set()
): SafetyContext {
  // Default heuristic coverage: any file containing `.test`, `.spec`, or a
  // sibling test discovered in well-known test directories is considered
  // partially covered.
  const coverage = new Map<string, number>();
  const testPattern = /\.(test|spec)\.(ts|tsx|js|jsx)$/i;
  const testDir = /(^|\/)(__tests__|tests|test)\//i;
  for (const f of files) {
    if (testPattern.test(f.path) || testDir.test(f.path)) {
      coverage.set(f.path, 1);
    }
  }
  return {
    testCoverage: coverage,
    autoGeneratedFiles,
    publicApiFiles,
  };
}

export function assessSafety(
  suggestion: RefactoringSuggestion,
  ctx: SafetyContext
): SafetyAssessment {
  const reasons: string[] = [];
  const warnings: string[] = [];
  let score = 1;

  if (ctx.autoGeneratedFiles.has(suggestion.file)) {
    score -= 0.9;
    warnings.push('Target file is auto-generated — manual edits will be overwritten.');
  }

  const coverage = ctx.testCoverage.get(suggestion.file) ?? 0;
  if (coverage <= 0) {
    score -= 0.35;
    warnings.push('No tests detected for this file — refactor regressions may go unnoticed.');
  } else if (coverage < 0.7) {
    score -= 0.15;
    warnings.push('Test coverage below 70%.');
  } else {
    reasons.push(`Test coverage ≈ ${Math.round(coverage * 100)}%.`);
  }

  if (suggestion.coupling >= 8) {
    score -= 0.25;
    warnings.push(`High coupling: ${suggestion.coupling} identifiers referenced.`);
  } else if (suggestion.coupling >= 5) {
    score -= 0.1;
    warnings.push(`Moderate coupling: ${suggestion.coupling} identifiers referenced.`);
  }

  if (suggestion.hasAnyType) {
    score -= 0.15;
    warnings.push('Target contains `any` types — type narrowing should precede refactoring.');
  }

  if (ctx.publicApiFiles.has(suggestion.file) && suggestion.isPublicApi) {
    score -= 0.2;
    warnings.push('Target file is part of the public API — consider deprecation steps.');
  }

  // Keep within [0, 1]
  score = Math.max(0, Math.min(1, score));
  const safeToAutoApply = score >= 0.85 && warnings.length === 0;

  if (reasons.length === 0) reasons.push('No risk-boosting factors detected.');

  return {
    safety: Number(score.toFixed(2)),
    reasons,
    warnings,
    safeToAutoApply,
  };
}
