#!/usr/bin/env node

import fs from "node:fs/promises";
import path from "node:path";
import process from "node:process";

function parseArgs(argv) {
  const args = {
    name: "",
    id: "",
    output: "",
    runtime: "iframe",
  };

  for (let index = 2; index < argv.length; index += 1) {
    const value = argv[index];
    const next = argv[index + 1];

    if (value === "--name" && next) {
      args.name = next;
      index += 1;
      continue;
    }

    if (value === "--id" && next) {
      args.id = next;
      index += 1;
      continue;
    }

    if (value === "--output" && next) {
      args.output = next;
      index += 1;
      continue;
    }

    if (value === "--runtime" && next) {
      args.runtime = next === "module" ? "module" : "iframe";
      index += 1;
    }
  }

  return args;
}

function buildManifest({ id, name, runtime }) {
  return {
    id,
    name,
    version: "0.1.0",
    description: `${name} plugin scaffold generated by the Stellar Dev Dashboard CLI.`,
    author: {
      name: "Your name",
    },
    permissions: ["dashboard:read"],
    runtime:
      runtime === "module"
        ? {
            mode: "module",
            entry: "./src/plugin.ts",
          }
        : {
            mode: "iframe",
            sandbox: ["allow-scripts"],
            srcDoc: "<!doctype html><html><body><div id=\"root\"></div></body></html>",
          },
    widgets: [
      {
        id: `${id}.settings`,
        title: name,
        placement: "settings",
        kind: runtime === "module" ? "react" : "iframe",
      },
    ],
    dataSources: [],
  };
}

function buildReadme({ name, id, runtime }) {
  return `# ${name}

Scaffolded plugin: \`${id}\`

## Runtime

\`${runtime}\`

## Next steps

1. Update the manifest and permission scopes.
2. Implement the widget UI.
3. Wire the plugin into your local extension host or static iframe server.
`;
}

function buildIframeHtml({ name, id }) {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>${name}</title>
    <style>
      html, body {
        margin: 0;
        min-height: 100%;
        background: #0c111b;
        color: #e8edf7;
        font-family: Inter, system-ui, sans-serif;
      }
      body {
        display: grid;
        place-items: center;
        padding: 20px;
      }
      .card {
        max-width: 520px;
        width: 100%;
        border-radius: 18px;
        border: 1px solid rgba(255,255,255,0.12);
        background: rgba(7, 11, 20, 0.9);
        padding: 20px;
      }
      h1 {
        margin: 0;
        font-size: 20px;
      }
      p {
        margin: 10px 0 0;
        color: #b6c0d4;
        line-height: 1.6;
        font-size: 13px;
      }
      code {
        display: inline-block;
        margin-top: 14px;
        padding: 4px 8px;
        border-radius: 999px;
        background: rgba(255,255,255,0.08);
        color: #7dd3fc;
        font-size: 11px;
      }
    </style>
  </head>
  <body>
    <div class="card">
      <h1>${name}</h1>
      <p>This scaffold starts as a sandboxed iframe plugin. Replace this content with your own UI.</p>
      <code>${id}</code>
    </div>
  </body>
</html>`;
}

async function main() {
  const args = parseArgs(process.argv);

  if (!args.name || !args.id || !args.output) {
    console.error(
      "Usage: node scripts/create-plugin.mjs --name \"My Plugin\" --id \"community.my-plugin\" --output ./my-plugin [--runtime iframe|module]"
    );
    process.exit(1);
  }

  const targetDir = path.resolve(process.cwd(), args.output);
  const srcDir = path.join(targetDir, "src");

  await fs.mkdir(srcDir, { recursive: true });

  const manifest = buildManifest(args);
  await fs.writeFile(path.join(targetDir, "plugin.json"), `${JSON.stringify(manifest, null, 2)}\n`);
  await fs.writeFile(path.join(targetDir, "README.md"), `${buildReadme(args)}\n`);
  await fs.writeFile(
    path.join(srcDir, "widget.html"),
    `${buildIframeHtml(args)}\n`
  );

  await fs.writeFile(
    path.join(targetDir, "package.json"),
    `${JSON.stringify(
      {
        name: args.id,
        private: true,
        version: "0.1.0",
      },
      null,
      2
    )}\n`
  );

  console.log(`Created plugin scaffold in ${targetDir}`);
}

main().catch((error) => {
  console.error(error?.message || String(error));
  process.exit(1);
});
